<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-P9AHAKG1" ignored="0" name="Default test" tests="4" failures="1" timestamp="17 Sep 2019 18:38:34 GMT" time="5.582" errors="0">
  <testcase name="delete_Test" time="3.344" classname="com.restassured.RestAssuredProject.RestAssuredmethodsTest"/>
  <testcase name="get_Test" time="0.259" classname="com.restassured.RestAssuredProject.RestAssuredmethodsTest">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;abc&amp;gt; but was:&amp;lt;cloudflare&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<abc> but was:<cloudflare>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.restassured.RestAssuredProject.RestAssuredmethodsTest.get_Test(RestAssuredmethodsTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- get_Test -->
  <testcase name="post_Test" time="1.38" classname="com.restassured.RestAssuredProject.RestAssuredmethodsTest"/>
  <testcase name="put_Test" time="0.532" classname="com.restassured.RestAssuredProject.RestAssuredmethodsTest"/>
</testsuite> <!-- Default test -->
